import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { GraphDoc } from "@patchcad/shared";
import type { Workspace } from "@patchcad/engine";
import { CodeContractPayload } from "./payload.js";

/**
 * Materializes the preview workspace at <ws.root>:
 *
 *   index.html
 *   src/main.tsx          generated glue: ParamsProvider + entry mount
 *   src/nodes/<id>.tsx    each node's artifact, verbatim
 *
 * Nodes import each other only via `@nodes/<id>` (aliased by the preview
 * server). Bare deps (react, @patchcad/preview-runtime) resolve up the tree
 * to the monorepo root node_modules.
 */

export async function assemble(graph: GraphDoc, ws: Workspace): Promise<void> {
  const srcDir = path.join(ws.root, "src");
  const nodesDir = path.join(srcDir, "nodes");
  await mkdir(nodesDir, { recursive: true });

  await writeFile(path.join(ws.root, "index.html"), indexHtml(graph), "utf8");
  await writeFile(path.join(srcDir, "main.tsx"), mainTsx(graph), "utf8");

  for (const node of Object.values(graph.nodes)) {
    if (!node.artifact) continue;
    await writeNodeModule(ws, node.id, node.artifact.code);
  }
}

/** Write (or overwrite) a single node's module — the hot-swap unit. */
export async function writeNodeModule(
  ws: Workspace,
  nodeIdValue: string,
  code: string,
): Promise<string> {
  const file = path.join(ws.root, "src", "nodes", `${nodeIdValue}.tsx`);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, code, "utf8");
  return file;
}

function indexHtml(graph: GraphDoc): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(graph.brief.goal || graph.id)} — patchcad preview</title>
  </head>
  <body>
    <div id="root"></div>
    <script>
      // Registers BEFORE the module graph loads: a crash during module
      // evaluation (import-time) must surface, not blank the pane.
      (function () {
        function report(message) {
          try { window.parent && window.parent.postMessage({ type: "patchcad:node:error", nodeId: "preview", message: message }, "*"); } catch (e) {}
          try {
            fetch("http://localhost:4100/api/preview-error", {
              method: "POST", headers: { "content-type": "application/json" },
              body: JSON.stringify({ message: message }),
            });
          } catch (e) {}
          var el = document.createElement("pre");
          el.style.cssText = "color:#ffb4b4;background:#2a1215;padding:12px;margin:12px;border-radius:6px;white-space:pre-wrap;font:12px/1.5 monospace;";
          el.textContent = message;
          document.body.appendChild(el);
        }
        window.addEventListener("error", function (e) { report(String((e.error && e.error.stack) || e.message)); });
        window.addEventListener("unhandledrejection", function (e) { report("unhandled rejection: " + String((e.reason && e.reason.stack) || e.reason)); });
      })();
    </script>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function mainTsx(graph: GraphDoc): string {
  const entry = graph.nodes[graph.assembly.entryNodeId];
  // A blank project (the studio's welcome state) has nothing to mount yet.
  if (!entry) {
    return `// GENERATED by patchcad — blank project placeholder\nexport {};\n`;
  }
  const payload = CodeContractPayload.parse(entry.contract.payload);
  const entryExport =
    payload.exports.find((e) => e.exportKind === "component")?.name ??
    payload.exports[0]!.name;

  const initialParams: Record<string, Record<string, unknown>> = {};
  for (const node of Object.values(graph.nodes)) {
    const defaults: Record<string, unknown> = {};
    for (const p of node.contract.params) defaults[p.name] = p.default;
    initialParams[node.id] = { ...defaults, ...node.params };
  }

  return `// GENERATED by patchcad — do not edit (regenerated on every assemble)
import React from "react";
import { createRoot } from "react-dom/client";
import { ParamsProvider, NodeErrorBoundary } from "@patchcad/preview-runtime";
import { ${entryExport} } from "@nodes/${entry.id}";

const initialParams = ${JSON.stringify(initialParams, null, 2)};

// A crashed preview must never be a silent blank pane: uncaught errors go to
// the studio (postMessage) AND the server log (fetch), and paint in-pane.
function reportFatal(message: string) {
  window.parent?.postMessage({ type: "patchcad:node:error", nodeId: "preview", message }, "*");
  void fetch("http://localhost:4100/api/preview-error", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ message }),
  }).catch(() => {});
  const el = document.createElement("pre");
  el.style.cssText = "color:#ffb4b4;background:#2a1215;padding:12px;margin:12px;border-radius:6px;white-space:pre-wrap;font:12px/1.5 monospace;";
  el.textContent = message;
  document.body.appendChild(el);
}
window.addEventListener("error", (e) => reportFatal(String(e.error?.stack ?? e.message)));
window.addEventListener("unhandledrejection", (e) => reportFatal("unhandled rejection: " + String((e.reason as Error)?.stack ?? e.reason)));

createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <ParamsProvider initial={initialParams}>
      <NodeErrorBoundary nodeId=${JSON.stringify(entry.id)}>
        <${entryExport} />
      </NodeErrorBoundary>
    </ParamsProvider>
  </React.StrictMode>,
);
`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
